source 'https://github.com/CocoaPods/Specs.git'
platform :ios, 7.0

target 'RMPZoomTransitionAnimator' do
  pod "RMPZoomTransitionAnimator", :path => "../"
end

target 'Tests' do
  pod "RMPZoomTransitionAnimator", :path => "../"
end
